# Generated by Django 3.2.8 on 2023-08-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
