# Generated by Django 3.0 on 2023-08-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0006_auto_20230807_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
