# Generated by Django 3.2.8 on 2023-07-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User_Management', '0003_auto_20230726_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('users', models.ManyToManyField(to='User_Management.Profile')),
            ],
        ),
    ]
