# Generated by Django 3.0 on 2023-08-02 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User_Management', '0001_initial'),
        ('Account_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User_Management.Profile'),
        ),
    ]
