# Generated by Django 3.2.8 on 2023-08-02 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0002_auto_20230802_0936'),
        ('Account_Management', '0003_alter_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Management.profile'),
        ),
    ]
