# Generated by Django 3.2.8 on 2023-08-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Management', '0004_alter_account_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='company_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
