# Generated by Django 3.2.8 on 2023-08-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Management', '0005_auto_20230802_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company_facebook',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='company_linkedin',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='company_twitter',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
