# Generated by Django 3.2.8 on 2023-08-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Management', '0006_auto_20230802_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company_video_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='viewed_employer_tutorial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='viewed_employer_welcome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
