# Generated by Django 3.2.8 on 2023-08-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Management', '0007_auto_20230802_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255, unique=True)),
                ('role_type', models.CharField(choices=[('admin', 'Admin'), ('hiring_manager', 'Hiring_Manager'), ('recruiter', 'Recruiter'), ('coordinator', 'Coordinator'), ('sourcer', 'Sourcer'), ('external_reviewer', 'External_Reviewer'), ('sub_reviewer', 'Sub_Reviewer')], max_length=255)),
                ('role_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['role_type'], name='Account_Man_role_ty_3bc181_idx'),
        ),
    ]
