# Generated by Django 3.2.8 on 2023-08-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Management', '0008_auto_20230802_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='company_industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
