# Generated by Django 3.2.8 on 2023-08-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Management', '0009_auto_20230802_1506'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company_name'], name='Account_Man_company_df2347_idx'),
        ),
    ]
