# Generated by Django 3.2.8 on 2023-08-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Management', '0010_account_account_man_company_df2347_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='company_website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
