# Generated by Django 3.2.8 on 2023-08-02 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0002_auto_20230802_0936'),
        ('Account_Management', '0011_auto_20230802_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(max_length=254)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account_Management.account')),
                ('invited_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to='User_Management.customuser')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account_Management.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations', to='User_Management.customuser')),
            ],
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['user'], name='Account_Man_user_id_b739f6_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['account'], name='Account_Man_account_816e84_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['invited_email'], name='Account_Man_invited_29c8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['is_accepted'], name='Account_Man_is_acce_e371fa_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['role'], name='Account_Man_role_id_a01a43_idx'),
        ),
    ]
