# Generated by Django 3.0 on 2023-08-10 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Management', '0018_auto_20230809_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvitation',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account_Management.Role'),
        ),
    ]
