# Generated by Django 3.2.8 on 2023-08-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Management', '0022_auto_20230817_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='department',
        ),
        migrations.RemoveField(
            model_name='account',
            name='office',
        ),
        migrations.RemoveField(
            model_name='account',
            name='organization',
        ),
    ]
