# Generated by Django 3.2.8 on 2023-08-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Management', '0023_auto_20230823_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_logo',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
