# Generated by Django 3.2.8 on 2023-08-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Management', '0024_alter_account_profile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_video',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
